name = "Binance"
uuid = "12345678-1234-5678-9012-123456789012"
version = "0.7.4"
authors = ["rzhli <tayuebuliuhen@gmail.com>"]

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OpenSSL = "4d8831e6-92b7-49fb-bdf8-b643e874388c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Crayons = "4"
DataFrames = "1.7.1"
FixedPointDecimals = "0.6.4"
OpenSSL = "1.6.1"
Printf = "1.11.0"
Sockets = "1.11.0"
StructTypes = "1.11.0"
URIs = "1.6.1"
julia = "1.11"
