name = "BinanceFIX"
uuid = "87654321-4321-8765-2109-876543210987"
version = "0.1.0"
authors = ["rzhli <tayuebuliuhen@gmail.com>"]

[deps]
Binance = "12345678-1234-5678-9012-123456789012"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[sources]
Binance = {path = ".."}

[compat]
julia = "1.11"
